<?php

namespace Subbotin\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GroupSharesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupSharesRepository extends EntityRepository
{
}
